<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Titel</name>
   <tag></tag>
   <elementGuidId>2d835bec-45c4-4916-bdbf-14121c8d3ef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;titeldesc&quot;]/select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;accordion-1&quot;]/table/tbody/tr[4]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;titeldesc&quot;]/select</value>
   </webElementProperties>
</WebElementEntity>
