<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Wetboek</name>
   <tag></tag>
   <elementGuidId>b9c0705f-86b6-44de-8be4-1e6f5f2193c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wetboek&quot;]/input[3]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wetboek&quot;]/input[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wetboek&quot;]/input[3]</value>
   </webElementProperties>
</WebElementEntity>
