<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframeWerkopdracht</name>
   <tag></tag>
   <elementGuidId>76cb3fd1-eb9f-43ac-bef0-d04d93d4d60c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id='iframeWerkopdracht']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@id='iframeWerkopdracht']</value>
   </webElementProperties>
</WebElementEntity>
