<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assistentie</name>
   <tag></tag>
   <elementGuidId>acf71e9b-d732-43fd-a2fe-77bda37fa851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[@class='uneven']//select[@name='sType']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;general-search&quot;]/table/tbody/tr/td/select[@name=&quot;sType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[@class='uneven']//select[@name='sType']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Actpol_Scripts/Iframe test env/Left frame ifrm87</value>
   </webElementProperties>
</WebElementEntity>
