<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>username</description>
   <name>userid</name>
   <tag></tag>
   <elementGuidId>c1daac24-53c5-40c3-b0a4-07ff796a5283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='nx_usr']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nx_usr&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='nx_usr']</value>
   </webElementProperties>
</WebElementEntity>
