<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ACTPOL-532</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>07719d17-8af1-4bca-ae8f-d24609ed7de7</testSuiteGuid>
   <testCaseLink>
      <guid>810f56c0-1e97-4f1f-8d28-611467259872</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JIRA Tasks/Release 6.6/ACTPOL-532</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a36234c3-cfe5-4113-9c2c-e8ac1b086506</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f829b33-91a6-4c0a-8a42-071d1628331a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beb7b3bb-adf4-4c6c-9333-4b9e06ef4427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1608e9e-828b-49d9-8495-dbd99186518d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
